question_data = [
    {
        "type": "boolean",
        "difficulty": "medium",
        "category": "Science: Computers",
        "question": "To bypass US Munitions Export Laws, the creator of the PGP published all the source code in book form. ",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "type": "boolean",
        "difficulty": "medium",
        "category": "Science: Computers",
        "question": "The HTML5 standard was published in 2014.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "type": "boolean",
        "difficulty": "hard",
        "category": "Science: Computers",
        "question": "The T-Mobile Sidekick smartphone is a re-branded version of the Danger Hiptop.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "type": "boolean",
        "difficulty": "hard",
        "category": "Science: Computers",
        "question": "DHCP stands for Dynamic Host Configuration Port.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "type": "boolean",
        "difficulty": "easy",
        "category": "Science: Computers",
        "question": "Pointers were not used in the original C programming language; they were added later on in C++.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "type": "boolean",
        "difficulty": "easy",
        "category": "Science: Computers",
        "question": "Linux was first created as an alternative to Windows XP.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "type": "boolean",
        "difficulty": "easy",
        "category": "Science: Computers",
        "question": "&quot;HTML&quot; stands for Hypertext Markup Language.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "type": "boolean",
        "difficulty": "medium",
        "category": "Science: Computers",
        "question": "Early RAM was directly seated onto the motherboard and could not be easily removed.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "type": "boolean",
        "difficulty": "easy",
        "category": "Science: Computers",
        "question": "The Windows 7 operating system has six main editions.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "type": "boolean",
        "difficulty": "medium",
        "category": "Science: Computers",
        "question": "Android versions are named in alphabetical order.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "type": "boolean",
        "difficulty": "easy",
        "category": "Science: Computers",
        "question": "The logo for Snapchat is a Bell.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "type": "boolean",
        "difficulty": "medium",
        "category": "Science: Computers",
        "question": "The very first recorded computer &quot;bug&quot; was a moth found inside a Harvard Mark II computer.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "type": "boolean",
        "difficulty": "easy",
        "category": "Science: Computers",
        "question": "In most programming languages, the operator ++ is equivalent to the statement &quot;+= 1&quot;.",
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "type": "boolean",
        "difficulty": "medium",
        "category": "Science: Computers",
        "question": "FLAC stands for &quot;Free Lossless Audio Condenser&quot;&#039;",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "type": "boolean",
        "difficulty": "medium",
        "category": "Science: Computers",
        "question": "The open source program Redis is a relational database server.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
]
